/* Banco de dados para usuarios, suas respostas e perfis de cargo */

CREATE DATABASE MAIN;

USE MAIN;

CREATE TABLE PERFIL (
    IDPERFIL INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(128) NOT NULL,
    RA INT(8) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE RESULTADO (
    IDRESULTADO INT PRIMARY KEY AUTO_INCREMENT,
    D_RESULT INT(3) NOT NULL,
    I_RESULT INT(3) NOT NULL,
    S_RESULT INT(3) NOT NULL,
    C_RESULT INT(3) NOT NULL,
    ANIMAL VARCHAR(10) NOT NULL
    ID_PERFIL INT,

    FOREIGN KEY ID_PERFIL(RESULTADO)
    REFERENCES IDPERFIL(PERFIL)
);
