CREATE TABLE PERFIL (
	CPF INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(255),
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	
);

CREATE TABLE COLABORADORES (
	CRACHA INT PRIMARY KEY AUTO_INCREMENT,
	CARGO VARCHAR(255),
	PRIMARY KEY (CRACHA)
	ID_SETOR INT,
	CPF_PERFIL INT

    FOREIGN KEY (CPF_PERFIL)
    REFERENCES PERFIL(CPF) ON DELETE CASCADE
	FOREIGN KEY (ID_SETOR)
    REFERENCES IDSETOR(SETOR) ON DELETE CASCADE
);

CREATE TABLE CURSO (
	ID_CURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_CURSO VARCHAR(255) NOT NULL UNIQUE,
);

CREATE TABLE SETOR (
	IDSETOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME_SETOR VARCHAR(255) NOT NULL UNIQUE,
	CRACHA_COLABORADORES INT

	FOREIGN KEY (CRACHA_COLABORADORES)
    REFERENCES COLABORADORES(CRACHA) ON DELETE CASCADE
);

CREATE TABLE ALUNO (
	RA INT PRIMARY KEY AUTO_INCREMENT,
	CPF_PERFIL FOREIGN KEY 

	FOREIGN KEY (CPF_PERFIL)
    REFERENCES PERFIL(CPF) ON DELETE CASCADE
);

CREATE TABLE CURSANDO (
	IDTURMA INT PRIMARY KEY AUTO_INCREMENT,
	RA_ALUNO INT,	
	ID_CURSO VARCHAR(255)

	FOREIGN KEY (RA_ALUNO)
    REFERENCES ALUNO(RA) ON DELETE CASCADE
	FOREIGN KEY (ID_CURSO)
    REFERENCES CURSO(IDCURSO) ON DELETE CASCADE
);

CREATE TABLE PERGUNTA (
	IDPERGUNTA INT PRIMARY KEY AUTO_INCREMENT,
	PERGUNTA VARCHAR(500) NOT NULL,
	NOME_TESTE VARCHAR(255) NOT NULL
);

CREATE TABLE HISTORICO_DISC (
	IDHISTORICO INT(255) PRIMARY KEY AUTO_INCREMENT,
	RESPOSTA VARCHAR(255) NOT NULL,
	DATA_ VARCHAR(255) NOT NULL,
	CPF_HISTORICO INT,
	ID_PERGUNTA INT
	
	FOREIGN KEY (CPF_HISTORICO)	
    REFERENCES ALUNO(CPF_ALUNO) ON DELETE CASCADE
	FOREIGN KEY (ID_PERGUNTA)
    REFERENCES PERGUNTA(IDPERGUNTA) ON DELETE CASCADE
);

CREATE TABLE GABARITO (
	IDGABARITO PRIMARY KEY AUTO_INCREMENT,
	ID_PERGUNTA INT,
	CLASSIFICACAO CHAR('D','I','S','C') NOT NULL,

	FOREIGN KEY (ID_PERGUNTA)
    REFERENCES PERGUNTA(IDPERGUNTA) ON DELETE CASCADE
);












